### ISSUE TITLE
Orthography Profile misses glottalized stops

### ISSUE THREAD

**Issue by LinguList** [lexibank/utoaztecan#6]
We have sequences like k+glottal stop, which is one sound. This should be double-checked.

**Comment by SimonGreenhill** [comment]
@LinguList  -- are you able to fix this?

**Comment by LinguList** [comment]
Yes, I am quite optimistic.

**Comment by LinguList** [comment]
Done now. @SimonGreenhill, in which repository is the code that we used to check for regularlity of human vs. automated cognates?

**Comment by LinguList** [comment]
We should run that again to make sure the results are compabitle.

**Comment by LinguList** [comment]
Sorry, in `scripts`, I'll check the code now!
